# Generated by Django 2.2.5 on 2021-08-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=100)),
                ('venue_id', models.CharField(default=None, max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('number_of_times', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=100)),
                ('venue_id', models.CharField(default=None, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default=None, max_length=100)),
                ('target', models.CharField(default=None, max_length=100)),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=8)),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_raw', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('paper_title', models.TextField()),
                ('paper_year', models.IntegerField(null=True)),
                ('venue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recommender.Venues')),
            ],
        ),
    ]
